### ISSUE TITLE
Not on PyPI despite the README

### ISSUE THREAD

**Issue by BertrandBordage** [springload/wagtailmodelchooser#1]
This module is not on PyPI, instead it’s this module: https://github.com/Naeka/wagtailmodelchooser
Another problem is that there’s not setup.py, so we can’t even install it using `pip install https://github.com/springload/wagtailmodelchooser/archive/master.tar.gz`.

**Comment by thibaudcolas** [comment]
Hey @BertrandBordage, thanks for the report. I've updated the README.

As you can see there has only been one commit in this repository, so the least I can say is that it's not ready for use yet.

If you do need a model chooser, the alternatives I know about are:

- https://github.com/takeflight/wagtailmodelchooser
- https://github.com/Naeka/wagtailmodelchooser
